### ISSUE TITLE
Unmapping K for man pages

### ISSUE THREAD

**Issue by barankarakus** [lambdalisue/vim-manpager#18]
Hey there,

I'm wondering how I might be able to stop K from opening the man page of the word under the cursor.

I've removed line 21 in ftplugin/man.vim, and this did the trick, but it got me wondering:

How does this plug-in actually work?

Would you mine giving me a brief overview? I don't know enough VimScript to delve into the code myself (heck, I don't even know what happens upon start-up!), but was hoping you could shed some light!

Thanks!

**Comment by NikoKS** [comment]
Had the same problem, puting this on after/ftplugin/man.vim works for me:
```
noremap <buffer><nowait> K <nop>
```
