### ISSUE TITLE
MAN pages with spaces throw exception

### ISSUE THREAD

**Issue by Konfekt** [lambdalisue/vim-manpager#4]
`:MAN git\ grep` and `:MAN 'git grep'` threw

``` vim
Error detected while processing function <SNR>221_MAN[7]..manpager#open[2]..manpager#load[1]..<SNR>309_args:
line    4:
E121: Undefined variable: s:man_sect_arg
E15: Invalid expression: [s:man_sect_arg, a:section, a:page]
Error detected while processing function <SNR>221_MAN[7]..manpager#open[2]..manpager#load:
line    1:
E712: Argument of extend() must be a List or Dictionary
```

**Comment by lambdalisue** [comment]
Prob. `$ man git-grep`

**Comment by Konfekt** [comment]
Works! How about catching spaces in `s:man_sect_arg` and throwing a more informative error instead, like `echoerr Spaces, ' ', not allowed. Use dashes, '-', instead!`

**Comment by Konfekt** [comment]
On a second thought: Best to replace all spaces by `-`. Because for example hitting `K` on the visual selection `git grep` looks for `git grep` and throws an error. Thus better look for `git-grep` right away.

**Comment by lambdalisue** [comment]
You are probably right. I'll think about that.

**Comment by lambdalisue** [comment]
@Konfekt Probably it is fixed now. Try the latest HEAD.

**Comment by Konfekt** [comment]
Thanks, works fine ! Now in shell as in Vim manpages with spaces are accepted.
