### ISSUE TITLE
add K for visual selections

### ISSUE THREAD

**Issue by Konfekt** [lambdalisue/vim-manpager#6]
Sometimes links are split at `-`, for example 

```
...git-
reflog ...
```

To jump to these links, how about extending `K` to visual selections by means of https://github.com/xolox/vim-notes/blob/d30601243d989c8df11956f0637106d7f255a051/autoload/xolox/notes.vim#L249
and a `nnoremap K :Man <c-r>=...` map?

**Comment by Konfekt** [comment]
Thinking about it:

Better use a mapping `nnoremap K :Man Cword()<cr>` with a function `Cword()`  that returns the word the cursor is at, but of the string obtained by joining the previous, current, and next line.

**Comment by lambdalisue** [comment]
I like the idea. If you send me a pr, I'll check it :-)

**Comment by Konfekt** [comment]
Ok, I'm at

``` vim
setlocal iskeyword+=-

let start = line('.')-1
let end = line('.')+1
let line = join(getline(start, end))

let curpos = len(getline(start)) + col('.')
```

Now how to get the `<cword>`at `curpos` in our string `line` ?
