### ISSUE TITLE
section number before page, e.g. man 3 glob

### ISSUE THREAD

**Issue by Konfekt** [lambdalisue/vim-manpager#8]
if the first argument for `Man` is a single number, say `Man 3 glob`, then man should open `glob(3)`. In particular, hitting `K` on `glob(3)` should invoke `Man 3 glob` and not `Man glob`.

**Comment by Konfekt** [comment]
In particular, `Man` should not replace a space ` `by`-`in that case (as now, for example`Man 3 glob`searches for`Man 3-glob`.

**Comment by lambdalisue** [comment]
Could you list up the possible patterns and expectations? I don't really know all patterns.

**Comment by Konfekt** [comment]
In fact, perhaps my previous suggestion was not a good one. On `ZSH`, typing `man git grep` would open `man git-grep` so I expected `:Man` to do the same.

Turns out, didn't know about it, that for example `man 3 glob` opens `glob(3)`, so a leading word of digits is always the section number. I pushed a commit for that. 

Accidentally both commits are now in the `patch-1` branch.

**Comment by lambdalisue** [comment]
> Accidentally both commits are now in the patch-1 branch.

Better to split the branch. Could you split it and `git push --force`? (from current master)

And also please refer this issue in the PR :-)
